name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Build'
        shell: bash
        run: |
          echo "::group::Build"
          yarn install --frozen-lockfile
          yarn build-storybook
          echo "::endgroup::"

      - name: 'upload'
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: ./storybook-static

      - id: deploy
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ github.token }}
